name: Task (addons-server)
description: Filing a task (contributors only)
title: "[Task]: "
labels: ["type:feature", "needs:info", "repository:addons-server"]
projects: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A few sentences describing what the task aims to achieve. It can be a simple sentence or a story formatted paragraph.
        Be concise and detailed. Avoid vague terms and include relevant links.
      placeholder: As a <blank>, I want to <blank, so that I can <blank>
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: Checks before submitting the issue
      options:
        - 
          label: Use task lists to track associated subtasks
          required: true
        -
          label: If the issue is ready to work on, remove the "needs:info" label
          required: true