name: Task (addons-server)
description: Filing a task (contributors only)
title: "[Task]: "
labels: ["type:feature", "needs:info", "repository:addons-server"]
projects: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A few sentences describing what the task aims to achieve. It can be a simple sentence or a story formatted paragraph.
        Be concise and detailed. Avoid vague terms and include relevant links.
      placeholder: As a <blank>, I want to <blank, so that I can <blank>
      value: ""
    validations:
      required: true
  - type: markdown
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: |
        List of milestones or checkpoints that if met verify the task has been completed.
      value: |
        ```[tasklist]
        ### Tasks
        ```