name: Default

on:
  release:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      boolean:
        description: 'A boolean input'
        default: true
        required: true
        type: boolean
      number:
        description: 'A number input'
        default: 0
        required: true
        type: number
      string:
        description: 'A string input'
        default: 'foo'
        required: true
        type: string
      optional:
        description: 'An optional input'
        default: 'fallback'
        required: false
        type: string
  repository_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  context:
    runs-on: ubuntu-latest

    outputs:
      boolean: ${{ steps.inputs.outputs.boolean }}
      number: ${{ steps.inputs.outputs.number }}
      string: ${{ steps.inputs.outputs.string }}
      optional: ${{ steps.inputs.outputs.optional }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/context

      - id: inputs
        shell: bash
        run: |
          boolean="${{ inputs.boolean || false }}"
          number="${{ inputs.number || 10 }}"
          string="${{ inputs.string || 'goodbye' }}"
          optional="${{ inputs.optional }}"

  call_worker:
    needs: context
    uses: ./.github/workflows/worker.yml
    with:
      boolean: ${{ needs.context.outputs.boolean }}
      number: ${{ needs.context.outputs.number }}
      string: ${{ needs.context.outputs.string }}
      optional: ${{ needs.context.outputs.optional }}
