name: Default

on:
  release:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      boolean:
        description: 'A boolean input'
        default: true
        required: true
        type: boolean
      number:
        description: 'A number input'
        default: 0
        required: true
        type: number
      string:
        description: 'A string input'
        default: 'foo'
        required: true
        type: string
      optional:
        description: 'An optional input'
        default: 'fallback'
        required: false
        type: string
  repository_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/context
  call_worker:
    uses: ./.github/workflows/worker.yml
    with:
      boolean: ${{ inputs.boolean }}
      number: ${{ inputs.number }}
      string: ${{ inputs.string }}
      optional: ${{ inputs.optional }}
