name: Push

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: context
        uses: ./.github/actions/context

      - uses: ./.github/actions/build
        with:
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          node_env: production
          latest: ${{ steps.context.outputs.is_release_master }}


