name: Push

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to staging
        run: |
          echo "Deploying to staging"
          # Your deployment script here
  deploy_production:
    runs-on: ubuntu-latest
    needs: deploy_staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to production
        run: |
          echo "Deploying to production"
          # Your deployment script here

